modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ruvaldak/translucencyfix/issues"
license = "MIT"

[[mods]]
modId = "translucencyfix"
version = "${version}"
displayName = "Translucency Fix"
logoFile="assets/translucencyfix/icon.png"
authors = "ruvaldak"
description = '''
enables translucency for HUD and GUIs in Minecraft
'''
#logoFile = ""

[[mixins]]
config = "translucencyfix-common.mixins.json"

[[dependencies.translucencyfix]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.translucencyfix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.0,)"
ordering = "NONE"
side = "BOTH"